services:
  app:
    build: .
    container_name: fontpreview_app
    restart: unless-stopped
    networks:
      - clearbook_net
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: "postgresql://clearbook_user:dw8AIdBKp856XKcqxU95x60Avz%2ByCS7teK3hUog83Gc%3D@clearbook_postgres:5432/fontpreview?schema=public"
      NEXTAUTH_URL: "https://fonts.wrobeldev.cloud"
      NEXTAUTH_SECRET: "2VOVaj1jyrhNSs3ui1Ggv8X1pbCnOXHvCZ23En4ied8="
      AUTH_TRUST_HOST: "true"
      SEED_ADMIN_EMAIL: "admin@wrobeldev.cloud"
      SEED_ADMIN_PASSWORD: "Y7da2jb6OH5udzluyZEkjvLRO91khrym1uyCvXfZpPs="
    volumes:
      # Keeping uploaded local fonts
      - fontpreview_fonts:/app/public/fonts

networks:
  clearbook_net:
    name: clearbook_clearbook-net
    external: true

volumes:
  fontpreview_db_data:
  fontpreview_fonts:
